spring:
  application:
    name: whitelist
  profiles:
    active: dev
  thymeleaf:
    mode: HTML5
server:
  servlet:
    context-path: /whitelist
  port: 8110

# jpa and datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database: MYSQL
    show_sql: false
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/whitelist?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: luke
    password: 123456

# debug sql mode
---
spring:
  profiles: dev_debug_sql
  jpa:
    show_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

# develop on desk top mode
---
spring:
  profiles: dev_desk
  datasource:
    url: jdbc:mysql://192.168.1.115:3306/whitelist?useSSL=false&useUnicode=true&characterEncoding=UTF-8
