spring:
  application:
    name: whitelist
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    mode: HTML5
server:
  servlet:
    context-path: /whitelist
  port: 8110

---
spring:
  profiles: dev
  jpa:
    database: MYSQL
    show_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/whitelist?useSSL=false
    username: luke
    password: 123456

---
spring:
  profiles: dev_desk
  datasource:
    url: jdbc:mysql://192.168.1.100:3306/whitelist?useSSL=false

---
spring:
  profiles: ut
  jpa:
    database: H2
    show_sql: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
